#TODO:  - Add cache usage at request
name: "Coverity tools for local analysis"
description: "Will download the given version of Coverity Analysis tools from given Coverity Connect and extract them into given folder. Will also add Coverity analysis tools into current runner PATH"
author: Jouni Lehto
branding:
  icon: shield
  color: blue
inputs:
  project:
    description: Project name in Coverity Connect, if not given then default=github.repository
    required: false
    default: ${{github.repository}}
  stream:
    description: Project stream name in Coverity Connect, if not given then default=github.ref_name
    required: false
    default: ${{github.ref_name}}
  cov_version:
    description: "What version of Coverity Analysis is needed, example: cov-analysis-linux64-2022.6.1"
    default: cov-analysis-linux64-2022.6.1
    required: false
  cov_url:
    description: URL for Coverity Connect where the analysis tar file can be downloaded
    required: true
  cov_username:
    description: Coverity Connect username
    required: true
  cov_password:
    description: Coverity Connect password
    required: true
  cov_license:
    description: Path to the license file. License is needed for analysis. If license file is not given, then it will be downloaded from the Coverity Connect Downloads.
    required: false
  cov_install_folder:
    description: To which folder the tools are extracted
    required: true
  cov_remove_folders:
    description: With this you can space separated list of folders which you are not needed from Coverity Analysis and that way safe some space. (by default are removed architecture-analysis sdk dynamic-analysis forcheck doc)
    required: false
    default: architecture-analysis sdk dynamic-analysis forcheck doc
  cov_configures:
    description: With this you can configure Coverity Analysis. (by default cov-configure --java && cov-configure --javascript && cov-configure --python && cov-configure --kotlin && cov-configure --gcc --xml-option=prepend_arg:--ppp_translator --xml-option=prepend_arg:"replace/#\s*error \"Do not include _sd-common.h directly; it is a private header.\"/" && cov-configure --template --compiler c++ --comptype gcc && cov-configure --template --compiler cc --comptype gcc)
    required: false
    default: cov-configure --java && cov-configure --javascript && cov-configure --python && cov-configure --kotlin && cov-configure --gcc --xml-option=prepend_arg:--ppp_translator --xml-option=prepend_arg:"replace/#\s*error \"Do not include _sd-common.h directly; it is a private header.\"/" && cov-configure --template --compiler c++ --comptype gcc && cov-configure --template --compiler cc --comptype gcc

runs:
  using: composite
  steps:
    # First step is to download the Coverity Analysis tar -file and extract it and remove not needed folders to minimize the needed space.
    - run: |
        : #Get Coverity Analysis tools from Coverity server and extract them and remove tools which are not needed
        mkdir -p ${{inputs.cov_install_folder}}
        curl -f -o ${{inputs.cov_install_folder}}/${{inputs.cov_version}}.tar.gz ${{inputs.cov_url}}/downloads/${{inputs.cov_version}}.tar.gz
        cd ${{inputs.cov_install_folder}} && tar -xf ${{inputs.cov_version}}.tar.gz
        cd ${{inputs.cov_version}} && rm -rf ${{inputs.cov_remove_folders}}
        if [ -z ${{inputs.cov_license}} ]
        then 
          curl -f -o ${{inputs.cov_install_folder}}/${{inputs.cov_version}}/bin/license.dat ${{inputs.cov_url}}/downloads/license.dat
        else
          cp ${{inputs.cov_license}} ${{inputs.cov_install_folder}}/${{inputs.cov_version}}/bin
        fi
      shell: bash
    # Second step is to add coverity bin -folder into runners PATH
    - run: echo "${{inputs.cov_install_folder}}/${{inputs.cov_version}}/bin" >> $GITHUB_PATH
      shell: bash
    # Third step is to set project and stream name as environmental params and replace special characters /%& and space to _
    # Project name can be found like ${{env.project}} and stream like ${{env.stream}}
    - name: Set Project and Stream names into env
      if: ${{inputs.project != '' && inputs.stream != ''}}
      run: |
        origin_name=${{inputs.project}}
        project_name=${origin_name//[\/ %&]/_}
        echo "project=$project_name" >> $GITHUB_ENV
        origin_stream_name=${{inputs.stream}}
        stream_name=${origin_stream_name//[\/ %&]/_}
        echo "stream=$stream_name" >> $GITHUB_ENV
      shell: bash
    - name: Set other env variables
      run: |
        echo "cov_url=${{inputs.cov_url}}" >> $GITHUB_ENV
        echo "cov_username=${{inputs.cov_username}}" >> $GITHUB_ENV
        echo "cov_password=${{inputs.cov_password}}" >> $GITHUB_ENV
        echo "cov_install_folder=${{inputs.cov_install_folder}}" >> $GITHUB_ENV
      shell: bash
    # Fourth step is to run Coverity configures.
    - name:
      if: ${{inputs.cov_configures != ''}}
      run: ${{inputs.cov_configures}}
      shell: bash
